import Head from 'next/head'
import Image from 'next/image'
import BackgroundImage from '../public/assets/splash.jpg'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image className='-z-10 absolute hidden md:grid md:object-cover h-screen' src={BackgroundImage} alt='splash-image'></Image>
      <main className='bg-black h-screen flex flex-col pl-5 md:pl-14 z-10 md:bg-opacity-80'>
        <div className='flex justify-end'>
          <div className='text-gray-500 font-bold text-xs md:text-md pr-5 pt-2 cursor-pointer hover:text-yellow-600 duration-300 w-fit font-montserrat'>
            about
          </div>
        </div>
        <div>
          <div id='intro' className='md:pt-24 text-4xl md:text-6xl max-w-2xl font-montserrat font-extrabold text-gray-300'>
            Attendance management for the modern classroom
          </div>
          <div id='button' className='w-fit cursor-pointer text-black font-montserrat font-extrabold md:text-lg text-sm pt-10'>
            <Link href={'/login'} className='bg-gray-300 w-fit p-3 rounded-xl duration-300 hover:rounded-sm hover:bg-yellow-600'>DIVE IN</Link>
          </div>
        </div>
      </main>
    </>
  )
}
